### ISSUE TITLE
streamlit app encountered an error,because  "panel" has been removed

### ISSUE THREAD

**Issue by QiYuewangLin** [edsaac/stpyvista#13]
Hi,
PyVistaDepted and is planned for future removal. pv.set_jupyter_backend('panel')
ValueError: Invalid Jupyter notebook plotting backend "panel".
Use one of the following:
"static", "client", "server", "trame", "none"

**Comment by edsaac** [comment]
Hi @QiYuewangLin, upgrading `stpyvista` to >=0.0.9 should take care of that.
