### ISSUE TITLE
[Feature Request] Autosize window to streamlit container width

### ISSUE THREAD

**Issue by BenGravell** [edsaac/stpyvista#15]
Love the work you've done! It would be awesome if the plot window could be autosized to the streamlit container width, instead of pegged to a fixed width.

**Comment by edsaac** [comment]
Just added a `use_container_width` argument to version `0.0.10`.  

![68747470733a2f2f692e666c756666792e63632f425067785a6b6d7372676d6663444644434e5743336d3443573067434a4637772e676966](https://github.com/edsaac/stpyvista/assets/34405119/9f4b54b0-923c-43fc-a096-a9c274199282)

Get the latest version:  `pip install stpyvista -U`
And check the demo app: [https://stpyvista.streamlit.app](https://stpyvista.streamlit.app)

**Comment by BenGravell** [comment]
🥇 my hero!

Upgraded & used in my app at https://structura.streamlit.app/ and it works beautifully! The stpyvista window adapts when resizing the browser window, as desired.
