### ISSUE TITLE
Coloration abnormalities

### ISSUE THREAD

**Issue by Bobosaver** [edsaac/stpyvista#19]
I want to color my VTK image.If I key "plotter.show()", it did great.But in stpyvista , there is an abnormality in the color.

![image](https://github.com/edsaac/stpyvista/assets/148194306/adc1b166-3a6e-437d-a4a9-a486092dc6e5)
![image](https://github.com/edsaac/stpyvista/assets/148194306/4bdc3334-4ee3-4258-80eb-cbce4bfedda1)

**Comment by edsaac** [comment]
I noticed that and it seems like a regression on the latest version of `panel`. Setting its version to `panel==1.3.8`  should work for now.

**Comment by Bobosaver** [comment]
But, a new error occur. it can not show my VTk,  just a output word.
![image](https://github.com/edsaac/stpyvista/assets/148194306/60793871-732f-4889-821b-362fe13e2195)

**Comment by edsaac** [comment]
I have seen that occasionally when running Python<=3.9, and it is part of the reason Python >= 3.10 is recommended. What version of Python are you running?

**Comment by edsaac** [comment]
> `slices = mesh.slice_orthogonal(x=u, y=v, z=w)`

[`slice_orthogonal`](https://docs.pyvista.org/version/stable/api/core/_autosummary/pyvista.DataSetFilters.slice_orthogonal.html#pyvista.DataSetFilters.slice_orthogonal) returns a [`pv.MultiBlock`](https://docs.pyvista.org/version/stable/api/core/_autosummary/pyvista.MultiBlock.html#pyvista-multiblock) object, which is basically a bundle of meshes. Iterating over the MultiBlock and adding each mesh individually to the plotter will do the trick.

![image](https://github.com/edsaac/stpyvista/assets/34405119/71bf3d7d-9d6d-4853-86bf-b30e0e108ba0)

****
This is a nice example that could go in the [Discussion](https://github.com/edsaac/stpyvista/discussions) section in this repo. 

```python
import pyvista as pv
from pyvista import examples
import streamlit as st
from stpyvista import stpyvista

pv.start_xvfb()

mesh = examples.load_channels()
add_mesh_kwargs = dict(cmap="copper", ambient=0.5)

## App layout
st.title("🍕 Slices & stpyvista")
cols = st.columns(2)

with cols[0]:
    "## Full 3D model"
    pl = pv.Plotter()
    pl.window_size = [300, 300]
    pl.add_mesh(mesh, **add_mesh_kwargs)
    pl.add_axes()
    pl.view_isometric()

    stpyvista(pl)

with cols[1]:
    "## Orthogonal slices"
    slices = mesh.slice_orthogonal(x=50, y=50, z=30)
    slices_pl = pv.Plotter()
    slices_pl.window_size = [300, 300]

    for slice in slices:
        slices_pl.add_mesh(slice, **add_mesh_kwargs)

    slices_pl.add_axes()
    slices_pl.view_isometric()
    stpyvista(slices_pl)

```

**Comment by Bobosaver** [comment]
thanks anyway,I will try it.

**Comment by edsaac** [comment]
Updating to `panel>=1.4.1` will solve the colormap issue.

https://github.com/holoviz/panel/issues/6627
