### ISSUE TITLE
problem with use stpyvista in streamlit cloud

### ISSUE THREAD

**Issue by DomenicoGaudioso** [edsaac/stpyvista#24]
Sure, here is an improved version of your questions in English for a forum:

---

Hi everyone,

I'm encountering an error when trying to import `stpyvista` in my project. Below are the screenshots of the error:

![Error importing stpyvista](https://github.com/edsaac/stpyvista/assets/43296235/631a2962-a6b7-42e6-b32f-b34ffeec5e50)

![Detailed error](https://github.com/edsaac/stpyvista/assets/43296235/ab9cf050-9260-4807-9837-a72210556a5e)

For context, here is my installation file:
- [packages.txt](https://github.com/user-attachments/files/15754138/packages.txt)
- [requirements.txt](https://github.com/user-attachments/files/15754139/requirements.txt)

Does anyone have any idea how to resolve this issue?

I have python 3.10

Thanks in advance for your help!

---

**Comment by edsaac** [comment]
Hi @DomenicoGaudioso , `requirements.txt` is for Python dependencies (stuff you would `pip install` ), whereas `packages.txt` is for other dependencies (stuff you would `apt install`). Check the [community cloud docs](https://docs.streamlit.io/deploy/streamlit-community-cloud/deploy-your-app/app-dependencies) for details on how to correctly configure those.  And for `stpyvista`, check the [readme](https://github.com/edsaac/stpyvista?tab=readme-ov-file#-deploying-to-streamlit-community-cloud ) file. 

You can also check [stpyvista's gallery app source code](https://github.com/edsaac/stpyvista-tests ) for an example of how to configure that.
