### ISSUE TITLE
Stpyvista not displaying .stl file when deployed on community cloud

### ISSUE THREAD

**Issue by TomCarts** [edsaac/stpyvista#25]
Hi there,

I have been using [@edsaac](https://discuss.streamlit.io/u/edsaac) stpyvista component to provide a visulisation to support an engineering optimisation exercise for a simple retaining wall calculation but I am having issues once deploying to the cloud.

The application runs fine when running locally, see snip below.

![image](https://github.com/edsaac/stpyvista/assets/164935873/65664985-1b59-4ffb-84f1-1af8b6321293)
But when I deploy it with recommended packages It doesn’t display anything, see snip below

![Uploading image.png…]()

And the code is here → [GitHub - TomCarts/L_Unit_Optimisation: Streamlit application for optimising an 'L' shaped retaining wall under global sliding and overturning 1](https://github.com/TomCarts/L_Unit_Optimisation.git)

Any help really appreciated

**Comment by edsaac** [comment]
Copy-pasting here my reply in the [Streamlit forum](https://discuss.streamlit.io/t/stpyvista-not-displaying-stl-file-when-deployed-on-community-cloud/73415/2):

> I managed to get the visualization going:
> 
> [https://edsaac-l-unit-optimisation-app-9grstx.streamlit.app/](https://edsaac-l-unit-optimisation-app-9grstx.streamlit.app/)
> 
> The issue seems to be that cadquery bundles an outdated version of vtk, which ends up conflicting with the vtk that pyvista uses as a dependency ([cadquery and vtk compatibility · Issue #23 · CadQuery/ocp-build-system · GitHub](https://github.com/CadQuery/ocp-build-system/issues/23)). Playing with the order the dependencies are resolved in the requirements.txt seems to do the trick.

I will mark this `cadquery` conflict as a known issue. 🦖
