### ISSUE TITLE
ImportError when importing stpyvista==0.1.2 within python <3.11

### ISSUE THREAD

**Issue by VasculatureModels** [edsaac/stpyvista#27]
Hi, 
It seems that importing stpyvista== 0.1.2 , causes an:
`ImportError: cannot import name 'Required' from 'typing'`
with python version < 3.11

Please, see discussion right there : 
[https://discuss.streamlit.io/t/high-memory-usage-when-displaying-stls-with-pyvista/82770](https://discuss.streamlit.io/t/high-memory-usage-when-displaying-stls-with-pyvista/82770)

**Comment by edsaac** [comment]
Thanks for catching that. Fixed with release v.0.1.3
