### ISSUE TITLE
Always show scalarbar

### ISSUE THREAD

**Issue by jvwilliams23** [edsaac/stpyvista#32]
Hi,

I have checked the other issues and also your gallery on streamlit cloud, I could not find an answer.

How do I keep the scalarbar shown at all times? In the sphere example on https://stpyvista.streamlit.app/ it is always shown. Other examples e.g. https://stpyvista.streamlit.app/?gallery=xyz have it hidden in the corner, which is what I am getting by default it seems. How to achieve the former?

Sorry if this has been answered before.

Best,
Josh

**Comment by edsaac** [comment]
Hi @jvwilliams23,

![image](https://github.com/user-attachments/assets/9fc2df4e-6426-449a-a5d8-5245f479d801)

The `panel` backend is used by default when you do

```py
from stpyvista import stpyvista
```

To get the view on the right, just swap the import line to use the `trame` backend

```py
from stpyvista.trame_backend import stpyvista
```

**Comment by edsaac** [comment]
Also, you might need to explicitly call [`plotter.add_scalar_bar(...)`](https://docs.pyvista.org/api/plotting/_autosummary/pyvista.plotter.add_scalar_bar)

**Comment by jvwilliams23** [comment]
Yes, changing backend to trame fixed it. Thanks!
